# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 52bb80804baf6a7c0b280649cfca3a4b9bf739fa3a1d28c960a3b49067f278e898041463c28744674701713fc94816393c65729ce920506212e5487a1f05a26f

test:
  secret_key_base: 8c3dc35204b4eeed98c7f823cb63ebe96f69c36770c65d5b5aaec81bb8c8481da704210d919c3406576c8b6fa2b9be9831590b6d6611f40df0370f0c51a07579

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
